services:
  healthcare-api:
    build:
      context: .
      dockerfile: Dockerfile

    image: healthcare-document-ai:latest
    container_name: healthcare-document-ai

    ports:
      - "8080:8080"

    env_file:
      - .env

    volumes:
      - healthcare-db:/app/data
      - healthcare-uploads:/app/Uploads

    restart: unless-stopped

volumes:
  healthcare-db:
  healthcare-uploads:
